// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Constante", Schema = "pamec")]
    public partial class Constante
    {
        public Constante()
        {
        }

        [Key]
        public int id { get; set; }
        public int idPadre { get; set; }
        public int codigo { get; set; }
       
    }
}