// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Pamec
{
    [Table("Entidad", Schema = "pamec")]
    public partial class Entidad
    {
        public Entidad()
        {
           
        }

        [Key]
        public int id { get; set; }
        
    }
}