// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Entities.Models.Sirep
{
    public partial class vsPrestadoresSedes
    {
        [StringLength(20)]
        public string CODIGODELAENTIDAD { get; set; }
        [StringLength(40)]
        public string NIT { get; set; }
        public int? IDTIPOIDENTIFICACION { get; set; }
        [StringLength(30)]
        public string TIPOIDENTIFICACION { get; set; }
        [StringLength(250)]
        public string NOMBREDESEDE { get; set; }
        [StringLength(250)]
        public string DIRECCIONSEDE { get; set; }
        [StringLength(25)]
        public string TELEFONOSEDE { get; set; }
        [StringLength(30)]
        public string FAXSEDE { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FECHADEINSCRIPCION { get; set; }
        public bool? IDSEDEPRINCIPAL { get; set; }
        [Required]
        [StringLength(15)]
        public string TIPODEENTIDAD { get; set; }
        [StringLength(101)]
        public string NOMBRESREPLEGAL { get; set; }
        [StringLength(101)]
        public string APELLIDOSREPLEGAL { get; set; }
        public int PRE_NID { get; set; }
        [StringLength(30)]
        public string CODIGODERAZONSOCIAL { get; set; }
        [StringLength(400)]
        public string NOMBREDERAZONSOCIAL { get; set; }
        [Required]
        [StringLength(50)]
        public string LOCALIDAD { get; set; }
        [StringLength(25)]
        public string TELPRESTADOR { get; set; }
        [StringLength(200)]
        public string DIRPRESTADOR { get; set; }
        [StringLength(150)]
        public string CORREOPRESTADOR { get; set; }
        [StringLength(1)]
        public string ESTADOSEDE { get; set; }
    }
}