// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("Criterio", Schema = "pamec")]
    public partial class Criterio
    {
        public Criterio()
        {
            Criterio_TipoDocumento = new HashSet<Criterio_TipoDocumento>();
            Criterio_reg_pamec = new HashSet<Criterio_reg_pamec>();
            Criterio_reg_sic = new HashSet<Criterio_reg_sic>();
        }

        [Key]
        public int id { get; set; }
        [Required]
        [StringLength(100)]
        public string nombre { get; set; }
        public bool estado { get; set; }
        [StringLength(10)]
        public string SOGCS { get; set; }

        [InverseProperty("idCriterioNavigation")]
        public virtual ICollection<Criterio_TipoDocumento> Criterio_TipoDocumento { get; set; }
        [InverseProperty("criterio")]
        public virtual ICollection<Criterio_reg_pamec> Criterio_reg_pamec { get; set; }
        [InverseProperty("criterio")]
        public virtual ICollection<Criterio_reg_sic> Criterio_reg_sic { get; set; }
    }
}