// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("Criterio_reg_pamec", Schema = "pamec")]
    public partial class Criterio_reg_pamec
    {
        [Key]
        public int id { get; set; }
        public int? criterioID { get; set; }
        public int? regPamecID { get; set; }
        public bool? aprobacion { get; set; }

        [ForeignKey(nameof(criterioID))]
        [InverseProperty(nameof(Criterio.Criterio_reg_pamec))]
        public virtual Criterio criterio { get; set; }
        [ForeignKey(nameof(regPamecID))]
        [InverseProperty(nameof(RegistroPAMEC.Criterio_reg_pamec))]
        public virtual RegistroPAMEC regPamec { get; set; }
    }
}