// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("Entidad", Schema = "pamec")]
    public partial class Entidad
    {
        public Entidad()
        {
            Firmas_Rep_Prestador = new HashSet<Firmas_Rep_Prestador>();
            Sede = new HashSet<Sede>();
        }

        [Key]
        public int id { get; set; }
        public int idTipoDocumento { get; set; }
        [Required]
        [StringLength(50)]
        public string numDocumento { get; set; }
        [Required]
        [StringLength(50)]
        public string codigo { get; set; }
        [Required]
        [StringLength(150)]
        public string razonSocial { get; set; }
        [Required]
        [StringLength(150)]
        public string nomRepresentanteLegal { get; set; }
        public int idTipoDocRepresLegal { get; set; }
        [Required]
        [StringLength(50)]
        public string numDocRepresLegal { get; set; }

        [ForeignKey(nameof(idTipoDocRepresLegal))]
        [InverseProperty(nameof(Constante.EntidadidTipoDocRepresLegalNavigation))]
        public virtual Constante idTipoDocRepresLegalNavigation { get; set; }
        [ForeignKey(nameof(idTipoDocumento))]
        [InverseProperty(nameof(Constante.EntidadidTipoDocumentoNavigation))]
        public virtual Constante idTipoDocumentoNavigation { get; set; }
        [InverseProperty("id_EntidadNavigation")]
        public virtual ICollection<Firmas_Rep_Prestador> Firmas_Rep_Prestador { get; set; }
        [InverseProperty("idEntidadNavigation")]
        public virtual ICollection<Sede> Sede { get; set; }
    }
}