// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("FirmaUsuarios", Schema = "pamec")]
    public partial class FirmaUsuarios
    {
        [Key]
        public int Id_Firma { get; set; }
        public string Firma { get; set; }
        public Guid? id_user { get; set; }

        [ForeignKey(nameof(id_user))]
        [InverseProperty(nameof(Usuario.FirmaUsuarios))]
        public virtual Usuario id_userNavigation { get; set; }
    }
}