// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("Firmas_Rep_Prestador", Schema = "pamec")]
    public partial class Firmas_Rep_Prestador
    {
        [Key]
        public int id { get; set; }
        public int? id_Entidad { get; set; }
        [Required]
        [StringLength(100)]
        public string tipoCargo { get; set; }
        public string firma { get; set; }
        public bool? activo { get; set; }

        [ForeignKey(nameof(id_Entidad))]
        [InverseProperty(nameof(Entidad.Firmas_Rep_Prestador))]
        public virtual Entidad id_EntidadNavigation { get; set; }
    }
}