// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Backend.Shared.Repositories
{
    [Table("Usuario_Cargo", Schema = "pamec")]
    public partial class Usuario_Cargo
    {
        public Usuario_Cargo()
        {
            SeguimientoPAMEC = new HashSet<SeguimientoPAMEC>();
        }

        [Key]
        public int id { get; set; }
        public int idCargo { get; set; }
        public bool estado { get; set; }
        [Column(TypeName = "date")]
        public DateTime? fechaInicio { get; set; }
        [Column(TypeName = "date")]
        public DateTime? fechaFin { get; set; }
        public Guid idUser { get; set; }

        [ForeignKey(nameof(idCargo))]
        [InverseProperty(nameof(Cargo.Usuario_Cargo))]
        public virtual Cargo idCargoNavigation { get; set; }
        [ForeignKey(nameof(idUser))]
        [InverseProperty(nameof(Usuario.Usuario_Cargo))]
        public virtual Usuario idUserNavigation { get; set; }
        [InverseProperty("idResponsableSeguimientoNavigation")]
        public virtual ICollection<SeguimientoPAMEC> SeguimientoPAMEC { get; set; }
    }
}