// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using Backend.Shared.Entities.Models.Sirep;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Backend.Shared.Repositories.Context
{
    public partial class dbaeusdsdevSirepContext : DbContext
    {
        public dbaeusdsdevSirepContext()
        {
        }

        public dbaeusdsdevSirepContext(DbContextOptions<dbaeusdsdevSirepContext> options)
            : base(options)
        {
        }

        public virtual DbSet<vsPrestadoresSedes> vsPrestadoresSedes { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<vsPrestadoresSedes>(entity =>
            {
                entity.HasNoKey();

                entity.ToView("vsPrestadoresSedes");

                entity.Property(e => e.APELLIDOSREPLEGAL).IsUnicode(false);

                entity.Property(e => e.CODIGODELAENTIDAD).IsUnicode(false);

                entity.Property(e => e.CODIGODERAZONSOCIAL).IsUnicode(false);

                entity.Property(e => e.CORREOPRESTADOR).IsUnicode(false);

                entity.Property(e => e.DIRECCIONSEDE).IsUnicode(false);

                entity.Property(e => e.DIRPRESTADOR).IsUnicode(false);

                entity.Property(e => e.ESTADOSEDE).IsUnicode(false);

                entity.Property(e => e.FAXSEDE).IsUnicode(false);

                entity.Property(e => e.LOCALIDAD).IsUnicode(false);

                entity.Property(e => e.NIT).IsUnicode(false);

                entity.Property(e => e.NOMBREDERAZONSOCIAL).IsUnicode(false);

                entity.Property(e => e.NOMBREDESEDE).IsUnicode(false);

                entity.Property(e => e.NOMBRESREPLEGAL).IsUnicode(false);

                entity.Property(e => e.TELEFONOSEDE).IsUnicode(false);

                entity.Property(e => e.TELPRESTADOR).IsUnicode(false);

                entity.Property(e => e.TIPODEENTIDAD).IsUnicode(false);

                entity.Property(e => e.TIPOIDENTIFICACION).IsUnicode(false);
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}